#when the player starts the game for the first time, each line has a fraction of a second delay
'hyperspacial transfer complete'
'checking systems'
'...'
'computer core: active'
'torch drive: standby'
'structural truss: 100% integrity'
'sensor suite: active'
'comunications laser: standby'
'navigation: ERROR! no nav-becons detected!'
'engaging celestial navigation'
'...'
'mapping complete, listing bodies'
'[0] Unnamed Class G2V star'
'[1] First planet, unamed Terestrial'
'[2] Second planet, unnamed Terestial'
'[3] Third planet, unnamed Jovian'
'end of list'
'...'
'imput comand or type HELP at any time for a list of options.'

#whenever the player engages the torch drive with the Goto comand.
'plotting brachistochrone trajectory'
'activating torch drive'
'deploying radator panels'
'magnetic containment active'
'warming plasma'
'fusion ignition'
'begining burn'
'...'
'...' #Some burns will have more lines of dots than others.
'...'
'...' #from here the next line segues into the destination's text.

#when the player returns to the deep space node.
'escape burn complete'
'navigation: celestial'
'listing bodies'
'[0] Unnamed Class G2V star'
'[1] First planet, unamed Terestrial'
'[2] Second planet, unnamed Terestial'
'[3] Third planet, unnamed Jovian'
'end of list'
'...'
'imput comand or type HELP at any time for a list of options.'


#list of comands displayed when the player types HELP
'The following comands can be used here.'
'SCAN [target]: scans an object, requires an active sensor suite'
'GOTO [target]: flies to a destination, requires an active torch drive'
'PING [target]: iluminates an object with comunications laser, requires an active comunications laser'
'STATUS: lists all modules and there states'
'HELP: displays this screen'
'end of list'
'...'
'imput comand or type HELP at any time for a list of options.'


#list of modules displayed when the player types STATUS, these lines will change as the statuses change.
'checking systems'
'...'
'computer core: active'
'torch drive: standby'
'structural truss: 100% integrity'
'sensor suite: active'
'comunications laser: standby'
'navigation: celestial'
'end of list'
'...'
'imput comand or type HELP at any time for a list of options.'
